### ISSUE TITLE
Unity Connect is going away feb 4th

### ISSUE THREAD

**Issue by chase-rg** [alelievr/MasterUnityHandles#1]
hey I just stumbled on your writeup at https://connect.unity.com/p/mastering-unityeditor-handles ...thanks for the detailed writeup!
I think unity connect is going to be disappearing soon, so you may want to migrate that article somewhere else so it's not lost. it's a good companion piece to this repo I think.  
Anyways just putting that out there for you!  Thanks!

**Comment by alelievr** [comment]
Hello, thanks for noticing me :)

I've migrated the content to the main page of the wiki here: https://github.com/alelievr/MasterUnityHandles/wiki

Not sure if Unity has a plan to migrate the content somewhere else, it'd be a shame to lose all this content :/
